<?php

defined('BASEPATH') OR exit('No direct script access allowed');

require APPPATH . '/libraries/REST_Controller.php';

use Restserver\Libraries\REST_Controller;


class v0 extends REST_Controller
{

    function __construct()
    {
        parent::__construct();
    }

    public function estadistica_get(){
		//comprobar entrada de dia mes o año, en cada caso es una consulta
        $query = $this->db->query("Aqui va consulta sql");//SELECT * FROM estadistica WHERE fecha BETWEEN '2017-03-19 00:00:00' AND '2017-03-19 23:59:59'
        $resultado = $query->result();
        $this->response($resultado, REST_Controller::HTTP_OK);

    }
	
	public function programacion_get(){
		$id=this->get('idArdu');
        $query = $this->db->query("Aqui va consulta sql");//SELECT Hora_ini, Hora_fin FROM arduino_programacion as ap, programacion WHERE ap.IDArduino=.$id
        $resultado = $query->result();
        $this->response($resultado, REST_Controller::HTTP_OK);

    }
	//update programacion y arduino
	public function estadistica_post()//comprobar post para insert
    {
        // $this->some_model->update_user( ... );
        $message = [
            'IDProg' => 100, // Automatically generated by the model
            'fecha' => $this->post('fecha'),//fecha del sistema, se hace con now()
            'temp' => $this->post('temp'),
			'hum' => $this->post('hum'),
			'litros' => $this->post('litros'),
			'idArd' => $this->post('idArd')
        ];

        $this->set_response($message, REST_Controller::HTTP_CREATED); // CREATED (201) being the HTTP response code
    }
	
	public function arduino_post()
    {
        
        $message = [
            'IDArduino' => $this->post('idArdu'),
            'Zona' => $this->post('zona')
        ];

        $this->set_response($message, REST_Controller::HTTP_CREATED); // CREATED (201) being the HTTP response code
    }
	
	public function prog_post()
    {
        
        $message = [
            'Arduino_IDArduino' => $this->post('idArdu'),
            'Programacion_IDProg' => $this->post('idProg')
        ];

        $this->set_response($message, REST_Controller::HTTP_CREATED); // CREATED (201) being the HTTP response code
    }
	
	public function arduprog_post()
    {
        
        $message = [
            'IDProg' => $this->post('id'),
            'Hora_ini' => $this->post('ini'),
            'Hora_fin' => $this->post('fin')
        ];

        $this->set_response($message, REST_Controller::HTTP_CREATED); // CREATED (201) being the HTTP response code
    }
	
	//falta delete para eliminar entradas en la BBDD
	
	/*public function hdad_get(){

        $dia = $this->get('dia');
        $id = $this->get('id');

        if ($id != NULL) {
            $query = $this->db->query("SELECT * FROM hermandades WHERE id =".$id);
            $resultado['hdad']['datos']= $query->row();
            $query = $this->db->query("SELECT nombre,posicion,historia,capataz FROM pasos WHERE idHermandad =".$id);
            $resultado['hdad']['pasos']= $query->result();
            $query = $this->db->query("SELECT descripcion,imgUrl,imgUrl2 FROM tunicas WHERE idHermandades =".$id);
            $resultado['hdad']['tunica']= $query->row();
            $query = $this->db->query("SELECT nombre,detrasDe FROM musica WHERE idHermandades =".$id);
            $resultado['hdad']['musica']= $query->result();
        }elseif ($dia != NULL){
            $query = $this->db->query("SELECT id,nombre,escudoUrl,imagen,retraso,inicio,fin FROM hermandades WHERE idDias =".$dia);
            $resultado['hdad']= $query->result();
        }else{
            $query = $this->db->query("SELECT h.id,h.nombre AS hdad,h.escudoUrl,h.nazarenos,d.nombre"
                ." FROM hermandades AS h JOIN dias AS d ON(h.idDias=d.id)");
            $resultado['hdad']= $query->result();
        }


        $this->response($resultado, REST_Controller::HTTP_OK);
    }
	public function contastes_user_insert_post()
	{
	
		$id_user = $this->input->get("id_user");
		$id_constante = $this->input->get("id_constante");
		$valor = $this->input->get("valor");		
		$query_inser = $this->db->query("INSERT INTO users_constantes (id_user,id_constante,valor)VALUES(".$id_user.",".$id_constante.",".$valor.")");
		
		if($query_inser){
			$this-> response($query_inser,201);
		}else{
			$this-> response($query_inser,500);
		}
		
	}

public function puntos_user_post()
	{
		$id = $this->input->get("id_user");
		$puntos = $this->input->get("puntos");
		$query_update = $this->db->query("UPDATE users SET puntuacion=".$puntos." WHERE id=".$id);
		
		
		if($query_update){
			$this-> response($query_update,201);
		}else{
			$this-> response($query_update,500);
		}
	
	*/
}
